### ISSUE TITLE
all config options with underscore are ignored

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/livekit-recorder#24]
the defaults options that have an underscore in their name are ignored
(audio_bitrate, audio_frequency, video_bitrate)
```
defaults:
  width: 320
  height: 200
  depth: 24
  framerate: 10
  audio_bitrate: 96
  audio_frequency: 22050
  video_bitrate: 750

```
with this yaml, I get the following result on the recorder's RecordingOptions

```
Defaults:
  width:320 
  height:200 
  depth:24 
  framerate:10 
  audio_bitrate:128 
  audio_frequency:44100 
  video_bitrate:4500
```
